name: Backend CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: nestjs_books
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Build the project
        working-directory: ./backend
        run: npm run build

      - name: Run Backend tests
        working-directory: ./backend
        run: npm run test

      # Build Docker image for the backend
      - name: Build Backend Docker image
        run: docker build -t nestjs-backend:V001 -f src/Dockerfile .

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Push Docker image to DockerHub
      - name: Push Backend Docker image
        run: docker push nestjs-backend:V001
