apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: alaminedocker/nestjs-backend:V001
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_HOST
              value: mysql
            - name: DATABASE_PORT
              value: '3308'
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: ''
            - name: DATABASE_NAME
              value: nestjs_books
