FROM node:18-alpine As development
# Create app directory
WORKDIR /app

# Copier les fichiers nécessaires depuis la racine du projet
COPY ../package*.json ./
COPY ../tsconfig.json ./
# Copy application dependency manifests to the container image.
# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
# Copying this first prevents re-running npm install on every code change.
COPY --chown=node:node package*.json ./

# Copier le répertoire src/books qui contient l'application NestJS
COPY . .
# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

# Bundle app source
COPY --chown=node:node . .

# Use the node user from the image (instead of the root user)
USER node
EXPOSE 3001
CMD [ "node", "dist/main.js" ]
